sudo: required
services:
  - docker

before_install: 
  - docker build -t saileshchandran/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saileshchandran/react-test npm test -- --coverage

after_success: 
  - docker build -t saileshchandran/multi-client ./client
  - docker build -t saileshchandran/multi-nginx ./nginx
  - docker build -t saileshchandran/multi-server ./server
  - docker build -t saileshchandran/multi-worker ./worker

  # login to docker-cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker-hub
  - docker push saileshchandran/multi-client
  - docker push saileshchandran/multi-nginx
  - docker push saileshchandran/multi-server
  - docker push saileshchandran/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: MultiDocker-env
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-806790321562
  bucket_path: docker-multi
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

    